// Phase 4 of docs/meeting-capture-plan.md: meeting notes generated by the
// operator's local agent, one project-memory entry per transcribed meeting
// through `recordEntry`, and the `recordings.keep` retention policy.
// Every function reports through the same action objects as the pipeline and
// never throws for a missing backend or memory section: the transcript is
// the deliverable, notes and memory are best effort on top of it.

import { copyFileSync, existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { detectBackend, runBackend } from "./backend.mjs";
import { recordEntry } from "./memory.mjs";
import { slugify } from "./meetings-core.mjs";

function action(kind, status, message, extra = {}) {
  return { kind, status, message, ...extra };
}

// ---------------------------------------------------------------------------
// Notes.
// ---------------------------------------------------------------------------

export function notesInstructions({ projectName, title, date }) {
  return [
    `You are writing the meeting notes for the project "${projectName}".`,
    `Meeting: ${title || "untitled"}, recorded on ${date}. The full transcript is the input.`,
    "Write the notes in the same language as the transcript, as Markdown only, with no preamble and no closing remarks.",
    "Use exactly these four sections, with the headings translated into that language:",
    "## Summary — five to eight sentences on what was discussed and concluded.",
    "## Decisions — one bullet per decision actually taken; write \"none\" if there were none.",
    "## Action items — one bullet per commitment: owner, action, and due date when one was said; write \"unassigned\" when the owner is unclear.",
    "## Open questions — one bullet per question left unanswered.",
    "Be factual: never invent names, numbers, or dates that are not in the transcript, and do not quote timestamps."
  ].join("\n");
}

export function notesFileName(naming, { timestamp, title }) {
  const date = `${timestamp.getFullYear()}-${String(timestamp.getMonth() + 1).padStart(2, "0")}-${String(timestamp.getDate()).padStart(2, "0")}`;
  const time = `${String(timestamp.getHours()).padStart(2, "0")}${String(timestamp.getMinutes()).padStart(2, "0")}`;
  return `${naming.replaceAll("{date}", date).replaceAll("{time}", time).replaceAll("{slug}", slugify(title))}.md`;
}

function notesHeader({ title, date, sourceName, transcriptRelative, backend, model, engine }) {
  return [
    `# ${title || "Meeting"} — ${date}`,
    "",
    `- Date: ${date}`,
    `- Recording: ${sourceName}`,
    `- Transcript: ${transcriptRelative}/transcript.txt`,
    `- Generated by: ${backend}${model ? ` (${model})` : ""} from a ${engine} transcript`,
    ""
  ].join("\n");
}

// The paragraph(s) under the first section heading, whatever language it is
// in: the summary is always the first "##" section by construction, and the
// file's own "# title" header (with its metadata list) sits above it.
export function summaryFromNotes(markdown) {
  const lines = String(markdown || "").split("\n");
  let first = lines.findIndex((line) => /^#{2,3}\s/.test(line));
  if (first === -1) first = lines.findIndex((line) => /^#\s/.test(line));
  if (first === -1) return String(markdown || "").trim().slice(0, 600);
  const body = [];
  for (const line of lines.slice(first + 1)) {
    if (/^#{1,3}\s/.test(line)) break;
    body.push(line);
  }
  return body.join("\n").trim().slice(0, 1200);
}

// Generates and files the notes for one transcript folder. `resolved` is the
// pipeline's resolution object (root, config, notesDirectory, naming,
// environment, projectName). Returns { notesPath, markdown } or null.
export function generateNotes(resolved, transcriptFolder, meta, { actions = [], dryRun = false, force = false } = {}) {
  if (!resolved.notesDirectory) return null;
  const transcriptRelative = path.relative(resolved.root, transcriptFolder);
  const transcriptPath = path.join(transcriptFolder, "transcript.txt");
  if (!existsSync(transcriptPath)) {
    actions.push(action("notes", "error", `${transcriptRelative}/transcript.txt is missing; nothing to write notes from.`));
    return null;
  }
  const timestamp = new Date(meta.recordedAt || Date.now());
  const date = meta.recordedAt ? String(meta.recordedAt).slice(0, 10) : new Date().toISOString().slice(0, 10);
  const notesPath = path.join(resolved.notesDirectory, notesFileName(resolved.naming, { timestamp, title: meta.title }));
  const notesRelative = path.relative(resolved.root, notesPath);
  if (existsSync(notesPath) && !force) {
    actions.push(action("notes", "kept", `${notesRelative} already exists (pass --force to regenerate).`));
    return { notesPath, markdown: readFileSync(notesPath, "utf8"), kept: true };
  }
  let detected;
  try {
    detected = detectBackend(resolved.environment);
  } catch (error) {
    actions.push(action("notes", "error", error instanceof Error ? error.message : String(error)));
    return null;
  }
  if (!detected.backend || !detected.installed) {
    actions.push(action("notes", "manual", `No local agent to write notes (${detected.reason}). In your next agent session run the meeting-notes skill on ${transcriptRelative}/, or \`nemeda-agent meeting notes ${transcriptRelative}\` once claude or codex is installed.`));
    return null;
  }
  if (dryRun) {
    actions.push(action("notes", "planned", `${transcriptRelative}/ -> ${notesRelative} with ${detected.backend}`));
    return null;
  }
  if (!existsSync(resolved.notesDirectory)) {
    actions.push(action("notes", "error", `Notes folder is missing: ${path.relative(resolved.root, resolved.notesDirectory)}/ (run \`nemeda-agent setup\` so the Drive link exists).`));
    return null;
  }
  const model = resolved.environment.NEMEDA_MEETINGS_MODEL || null;
  const result = runBackend({
    backend: detected.backend,
    model,
    instructions: notesInstructions({ projectName: resolved.projectName, title: meta.title, date }),
    cwd: transcriptFolder,
    inputFile: "transcript.txt",
    input: readFileSync(transcriptPath, "utf8")
  }, resolved.environment);
  if (result.error) {
    actions.push(action("notes", "error", `${detected.backend} could not write the notes: ${result.error}`));
    return null;
  }
  const markdown = `${notesHeader({ title: meta.title, date, sourceName: meta.sourceName, transcriptRelative, backend: detected.backend, model, engine: meta.engine })}\n${result.text.trim()}\n`;
  mkdirSync(path.dirname(notesPath), { recursive: true });
  writeFileSync(notesPath, markdown);
  actions.push(action("notes", "created", `${notesRelative} written by ${detected.backend} in ${Math.round(result.ms / 1000)}s.`, { notes: notesRelative }));
  return { notesPath, markdown };
}

// ---------------------------------------------------------------------------
// Memory.
// ---------------------------------------------------------------------------

export function recordMeetingMemory(resolved, transcriptFolder, meta, notes, { actions = [], dryRun = false } = {}) {
  if (resolved.config.memory === false) return null;
  const transcriptRelative = path.relative(resolved.root, transcriptFolder);
  const date = meta.recordedAt ? String(meta.recordedAt).slice(0, 10) : new Date().toISOString().slice(0, 10);
  const title = `${meta.title || "Meeting"} (${date})`;
  if (dryRun) {
    actions.push(action("memory", "planned", `record "${title}" in the project memory`));
    return null;
  }
  const summary = (notes?.markdown && summaryFromNotes(notes.markdown))
    || `Transcript filed at ${transcriptRelative}/. ${readFileSync(path.join(transcriptFolder, "transcript.txt"), "utf8").trim().slice(0, 500)}`;
  const entry = recordEntry(resolved.root, {
    type: "meeting",
    title,
    summary,
    date,
    author: resolved.environment.GIT_AUTHOR_EMAIL || undefined,
    tags: ["meeting"],
    source: {
      kind: "meeting",
      transcript: transcriptRelative,
      notes: notes?.notesPath ? path.relative(resolved.root, notes.notesPath) : null,
      recording: meta.sourceName,
      engine: meta.engine,
      host: meta.host
    }
  });
  if (!entry) {
    actions.push(action("memory", "skipped", "Project memory not configured (or no git user.email); add a `memory` section to log meetings."));
    return null;
  }
  actions.push(action("memory", "created", `Memory entry ${entry.id} in ${path.relative(resolved.root, entry.path)}.`, { memory: entry.id }));
  return entry;
}

// ---------------------------------------------------------------------------
// Retention: what happens to the recording once its transcript exists.
// ---------------------------------------------------------------------------

function moveFile(source, target) {
  try {
    renameSync(source, target);
  } catch (error) {
    if (error?.code !== "EXDEV") throw error;
    copyFileSync(source, `${target}.part`);
    renameSync(`${target}.part`, target);
    unlinkSync(source);
  }
}

// `archive`: move the recording right after its transcript is filed.
export function archiveRecording(resolved, recordingPath, { actions = [], dryRun = false } = {}) {
  const policy = resolved.config.recordings;
  if (!policy || policy.keep !== "archive") return null;
  const archiveDirectory = path.join(resolved.root, policy.path);
  const target = path.join(archiveDirectory, path.basename(recordingPath));
  const relativeTarget = path.relative(resolved.root, target);
  if (dryRun) {
    actions.push(action("recording", "planned", `move ${path.basename(recordingPath)} to ${path.relative(resolved.root, archiveDirectory)}/`));
    return null;
  }
  if (!existsSync(recordingPath)) return null;
  if (existsSync(target)) {
    actions.push(action("recording", "kept", `${relativeTarget} already exists; the recording stays where it is.`));
    return null;
  }
  try {
    mkdirSync(archiveDirectory, { recursive: true });
    moveFile(recordingPath, target);
    actions.push(action("recording", "created", `${path.basename(recordingPath)} archived to ${path.relative(resolved.root, archiveDirectory)}/.`));
    return target;
  } catch (error) {
    actions.push(action("recording", "error", `Could not archive ${path.basename(recordingPath)}: ${error instanceof Error ? error.message : String(error)}`));
    return null;
  }
}

// `delete` after N days: sweep a state's processed entries. Only recordings
// whose transcript folder still exists are deleted, and only once.
export function sweepDeletions(resolved, state, { actions = [], dryRun = false, now = Date.now(), resolvePath = (entry) => entry.path } = {}) {
  const policy = resolved.config.recordings;
  if (!policy || policy.keep !== "delete") return 0;
  const cutoff = now - policy.afterDays * 86_400_000;
  let deleted = 0;
  for (const entry of state.processed) {
    if (!entry.transcript || entry.deletedAt || !entry.processedAt) continue;
    if (Date.parse(entry.processedAt) > cutoff) continue;
    if (!existsSync(path.join(resolved.root, entry.transcript))) continue;
    const filePath = resolvePath(entry);
    if (!existsSync(filePath)) {
      entry.deletedAt = new Date(now).toISOString();
      continue;
    }
    if (dryRun) {
      actions.push(action("recording", "planned", `delete ${path.basename(filePath)} (transcribed ${policy.afterDays}+ days ago)`));
      continue;
    }
    try {
      unlinkSync(filePath);
      entry.deletedAt = new Date(now).toISOString();
      deleted += 1;
      actions.push(action("recording", "created", `Deleted ${path.basename(filePath)}: transcribed more than ${policy.afterDays} days ago.`));
    } catch (error) {
      actions.push(action("recording", "error", `Could not delete ${path.basename(filePath)}: ${error instanceof Error ? error.message : String(error)}`));
    }
  }
  return deleted;
}
